analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.9408602
  brandStrength: 0.8046595
  lightness: 0.03942652
  brandColors:
    - '#CFCFCF'
    - '#333333'
    - '#5C5C5C'
  rhythmicContrast: 0.7473118
typography_spectrum: 0.3960573
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.9215273486915976
favicon: null
name: timjwilson
